### PR TITLE
Update intervaltree version to >= 3.0.0

### PR DESCRIPTION
**Pull request by AndrewLvov**

### CODE REVIEW

**Comment by Julian** [comment]
Is this correct? The only reason we would want to pin this from below would be for newer ebb-lints, which also pin this correctly -- but if anything used an older version of ebb-lint, they'd be broken by this pin

**Comment by AndrewLvov** [comment]
@Julian I don't know why it's not pinned when used as a dependency, please look at this:
https://jenkins.mgnt.in/blue/organizations/jenkins/Magnetic%2FFloodgate/detail/hide-deprecation-warnings/1/pipeline

**Comment by AndrewLvov** [comment]
@Julian ah, actually I can remove the requirement now.

**Comment by AndrewLvov** [comment]
Removed

**Pull request merged**
